export const INITIAL_ATTENDANCE = [
  { id: "prev-29", dayNumber: 29, isPrevMonth: true, status: "empty" },
  { id: "prev-30", dayNumber: 30, isPrevMonth: true, status: "empty" },
  { id: "prev-31", dayNumber: 31, isPrevMonth: true, status: "empty" },

  {
    id: "oct-1",
    dayNumber: 1,
    status: "present",
    inTime: "09:02 AM",
    outTime: "06:04 PM",
  },
  {
    id: "oct-2",
    dayNumber: 2,
    status: "present",
    inTime: "08:58 AM",
    outTime: "06:01 PM",
  },
  {
    id: "oct-3",
    dayNumber: 3,
    status: "late",
    inTime: "09:18 AM",
    outTime: "06:02 PM",
  },
  {
    id: "oct-4",
    dayNumber: 4,
    status: "present",
    inTime: "09:01 AM",
    outTime: "06:05 PM",
  },
  {
    id: "oct-5",
    dayNumber: 5,
    status: "today",
    inTime: "09:00 AM",
    outTime: null,
    liveHours: "08h 12m",
  },

  { id: "oct-6", dayNumber: 6, status: "present", inTime: "08:57 AM" },
  { id: "oct-7", dayNumber: 7, status: "weekend" },
  { id: "oct-8", dayNumber: 8, status: "weekend" },
  { id: "oct-9", dayNumber: 9, status: "present", inTime: "09:03 AM" },
  { id: "oct-10", dayNumber: 10, status: "absent" },
  { id: "oct-11", dayNumber: 11, status: "present", inTime: "08:59 AM" },
  { id: "oct-12", dayNumber: 12, status: "present", inTime: "09:04 AM" },
  { id: "oct-13", dayNumber: 13, status: "present", inTime: "08:55 AM" },
  { id: "oct-14", dayNumber: 14, status: "weekend" },
  { id: "oct-15", dayNumber: 15, status: "weekend" },
  { id: "oct-16", dayNumber: 16, status: "late", inTime: "09:16 AM" },
  { id: "oct-17", dayNumber: 17, status: "present", inTime: "08:52 AM" },
  { id: "oct-18", dayNumber: 18, status: "present", inTime: "09:05 AM" },
  { id: "oct-19", dayNumber: 19, status: "present", inTime: "08:57 AM" },
  { id: "oct-20", dayNumber: 20, status: "present", inTime: "09:00 AM" },
  { id: "oct-21", dayNumber: 21, status: "weekend" },
  { id: "oct-22", dayNumber: 22, status: "weekend" },
  { id: "oct-23", dayNumber: 23, status: "present", inTime: "08:55 AM" },
  { id: "oct-24", dayNumber: 24, status: "present", inTime: "09:03 AM" },
  { id: "oct-25", dayNumber: 25, status: "present", inTime: "08:58 AM" },
  { id: "oct-26", dayNumber: 26, status: "present", inTime: "09:00 AM" },
  { id: "oct-27", dayNumber: 27, status: "present", inTime: "09:01 AM" },
  { id: "oct-28", dayNumber: 28, status: "weekend" },
  { id: "oct-29", dayNumber: 29, status: "weekend" },
  { id: "oct-30", dayNumber: 30, status: "present", inTime: "09:02 AM" },
  { id: "oct-31", dayNumber: 31, status: "present", inTime: "08:56 AM" },

  { id: "next-1", dayNumber: 1, isNextMonth: true, status: "empty" },
  { id: "next-2", dayNumber: 2, isNextMonth: true, status: "empty" },
  { id: "next-3", dayNumber: 3, isNextMonth: true, status: "empty" },
  { id: "next-4", dayNumber: 4, isNextMonth: true, status: "empty" },
];

export const INITIAL_TIMELINE = [
  {
    id: 1,
    title: "Punched In",
    description: "09:00 AM • Noida Office",
    type: "success",
  },
  {
    id: 2,
    title: "Currently Active",
    description: "Live tracking session",
    type: "warning",
  },
];